name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  tests:
    uses: ./.github/workflows/ci.yml

  pypi-publish:
    needs: tests
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/stagpy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
